# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1bHRldndmcXR3eXV1cXV6Z2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjUzMjg3NDAsImV4cCI6MjA0MDkwNDc0MH0.zD8kOrQJrhklizigzBzdYqjEJ_nHCX_ITxORk9TpXvg"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1bHRldndmcXR3eXV1cXV6Z2N1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNTMyODc0MCwiZXhwIjoyMDQwOTA0NzQwfQ.5wG-wVP9IUVckebFhYZqxXoDEu4m_iPAC-kjqJ-QEVc"
